export const mockData = [
  {
    floorName: '4',
    rooms: [
      {
        roomName: '401',
        roomType: 'DLXD',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '402',
        roomType: 'DLXTB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '403',
        roomType: 'DLXTB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '404',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '405',
        roomType: 'FAM',
        clientNumber: 4,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '406',
        roomType: 'SUPT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '407',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '408',
        roomType: 'SUPD',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '409',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '410',
        roomType: 'SUPT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '411',
        roomType: 'DLXDB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '412',
        roomType: 'DLXDB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '5',
    rooms: [
      {
        roomName: '501',
        roomType: 'DLXD',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: true,
        isNameRed: false,
      },
      {
        roomName: '502',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '503',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '504',
        roomType: 'SUPT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '505',
        roomType: 'FAM',
        clientNumber: 3,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '506',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '507',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '508',
        roomType: 'SUPD',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '509',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '510',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '511',
        roomType: 'DLXDB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: 'red',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '512',
        roomType: 'DLXDB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '6',
    rooms: [
      {
        roomName: '601',
        roomType: 'DLXD',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '602',
        roomType: 'DLXTB',
        clientNumber: 4,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: true,
      },
      {
        roomName: '603',
        roomType: 'DLXTB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '604',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '605',
        roomType: 'FAM',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '606',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '607',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '608',
        roomType: 'SUPD',
        clientNumber: 1,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '609',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '610',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '611',
        roomType: 'DLXDB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '612',
        roomType: 'DLXDB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '7',
    rooms: [
      {
        roomName: '701',
        roomType: 'DLXD',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '702',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: true,
      },
      {
        roomName: '703',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: 'red',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '704',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '705',
        roomType: 'FAM',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '706',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '707',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '708',
        roomType: 'SUPD',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '709',
        roomType: 'SUPTR',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '710',
        roomType: 'SUPT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '711',
        roomType: 'DLXDB',
        clientNumber: 1,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '712',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '8',
    rooms: [
      {
        roomName: '801',
        roomType: 'DLXD',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '802',
        roomType: 'DLXTB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '803',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '804',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '805',
        roomType: 'FAM',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '806',
        roomType: 'SUPT',
        clientNumber: 2,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'red',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '807',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '808',
        roomType: 'SUPD',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '809',
        roomType: 'SUPTR',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '810',
        roomType: 'SUPT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '811',
        roomType: 'DLXDB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '812',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '9',
    rooms: [
      {
        roomName: '901',
        roomType: 'DLXD',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '902',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '903',
        roomType: 'DLXTB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '904',
        roomType: 'SUPT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: 'red',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '905',
        roomType: 'FAM',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '906',
        roomType: 'SUPT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: 'red',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '907',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '908',
        roomType: 'SUPD',
        clientNumber: 1,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '909',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '910',
        roomType: 'SUPT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '911',
        roomType: 'DLXDB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '912',
        roomType: 'DLXDB',
        clientNumber: 1,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '10',
    rooms: [
      {
        roomName: '1001',
        roomType: 'DLXD',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1002',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1003',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1004',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1005',
        roomType: 'FAM',
        clientNumber: 4,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1006',
        roomType: 'SUPTR',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1007',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1008',
        roomType: 'SUPTR',
        clientNumber: 1,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1009',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1010',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1011',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1012',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '11',
    rooms: [
      {
        roomName: '1101',
        roomType: 'DLXD',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1102',
        roomType: 'DLXTB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: 'red',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1103',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1104',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: 'red',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1105',
        roomType: 'FAM',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1106',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: 'red',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1107',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1108',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1109',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1110',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1111',
        roomType: 'DLXDB',
        clientNumber: 1,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1112',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '12',
    rooms: [
      {
        roomName: '1201',
        roomType: 'DLXD',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1202',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1203',
        roomType: 'DLXTB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1204',
        roomType: 'DLXT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1205',
        roomType: 'FAM',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1206',
        roomType: 'DLXT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1207',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1208',
        roomType: 'DLXT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1209',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1210',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1211',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1212',
        roomType: 'DLXDB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '14',
    rooms: [
      {
        roomName: '1401',
        roomType: 'DLXD',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1402',
        roomType: 'DLXTB',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1403',
        roomType: 'DLXTB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1404',
        roomType: 'DLXT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1405',
        roomType: 'FAM',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1406',
        roomType: 'DLXT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1407',
        roomType: 'SUPTR',
        clientNumber: 1,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1408',
        roomType: 'DLXT',
        clientNumber: 2,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1409',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đang sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1410',
        roomType: 'DLXT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1411',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1412',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
  {
    floorName: '15',
    rooms: [
      {
        roomName: '1501',
        roomType: 'JST',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1502',
        roomType: 'DLXTB',
        clientNumber: 3,
        status: 'Đã sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: 'red',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1504',
        roomType: 'DLXT',
        clientNumber: 2,
        status: 'Đã sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1505',
        roomType: 'FAM',
        clientNumber: 3,
        status: 'Đã sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1506',
        roomType: 'DLXT',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: 'green',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1507',
        roomType: 'SUPTR',
        clientNumber: 3,
        status: 'Đã sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1508',
        roomType: 'DLXT',
        clientNumber: 3,
        status: 'Đã sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1509',
        roomType: 'SUPTR',
        clientNumber: 2,
        status: 'Đã sử dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1510',
        roomType: 'DLXT',
        clientNumber: 4,
        status: 'Đã sửu dụng',
        isOccupied: true,
        isClean: false,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1511',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
      {
        roomName: '1512',
        roomType: 'DLXDB',
        clientNumber: 0,
        status: 'Trống',
        isOccupied: false,
        isClean: true,
        dotColor: '',
        isLocked: false,
        isNameRed: false,
      },
    ],
  },
]
